# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Claire Morduch
subtitle: Non-profit Consultant
email: clairemorduch@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Claire Morduch brings a wealth of experience consulting to a 
  variety of nonprofit organizations from across a range of sectors.
baseurl: "/clairemorduch" # the subpath of your site, e.g. /blog
mediaurl: "/media" # the subpath for images
url: "http://littleweaver.github.io" # the base hostname & protocol for your site
# twitter_username: clairemorduch
# github_username:  clairemorduch

# Build settings
markdown: kramdown
